export const random_words = [
    "the ", "a ", "an ", "and ", "or ", "but ", "if ", "because ", "as ", "when ", "while ", "of ", 
    "for ", "to ", "on ", "in ", "with ", "about ", "at ", "by ", "from ", "above ", "below ", 
    "over ", "under ", "between ", "among ", "through ", "during ", "before ", "after ", 
    "against ", "along ", "apple ", "banana ", "cherry ", "dog ", "elephant ", "flower ", 
    "guitar ", "house ", "island ", "jungle ", "kite ", "lemon ", "mountain ", "notebook ", 
    "orange ", "piano ", "quartz ", "river ", "sunshine ", "tree ", "umbrella ", "village ", 
    "whale ", "xylophone ", "yacht ", "zebra ", "cloud ", "dragon ", "eagle ", "forest ", 
    "garden ", "honey ", "igloo ", "jacket ", "kangaroo ", "ladder ", "moon ", "night ", 
    "ocean ", "puzzle ", "queen ", "robot ", "star ", "tiger ", "universe ", "violet ", 
    "window ", "xenon ", "yellow ", "zoo ", "bridge ", "castle ", "diamond ", "energy ", 
    "feather ", "galaxy ", "horizon ", "ice ", "jewel ", "koala ", "library ", "mirror ", 
    "nest ", "owl ", "parrot ", "quiver ", "rose ", "snow ", "train ", "umbrella ", "violin ", 
    "wind ", "yoga ", "zenith ", "ant ", "book ", "cup ", "door ", "engine ", "fire ", 
    "grape ", "hat ", "insect ", "key ", "lamp ", "melon ", "nut ", "oasis ", "paint ", 
    "queen ", "rocket ", "shell ", "tornado ", "utensil ", "vase ", "wall ", "xerox ", 
    "yo-yo ", "zipper ", "chair ", "desk ", "phone ", "television ", "computer ", "glasses ", 
    "pen ", "pencil ", "notebook ", "bottle ", "backpack ", "window ", "curtain ", "carpet ", 
    "pillow ", "blanket ", "chair ", "sofa ", "table ", "mirror ", "clock ", "watch ", 
    "shoe ", "sock ", "shirt ", "pants ", "coat ", "hat ", "scarf ", "glove ", "wallet ", 
    "purse ", "key ", "book ", "magazine ", "newspaper ", "folder ", "paper ", "towel ", 
    "dish ", "cup ", "plate ", "fork ", "knife ", "spoon ", "stove ", "oven ", "fridge ", 
    "sink ", "toaster ", "blender ", "microwave ", "phone ", "charger ", "headphones ", 
    "laptop ", "tablet ", "speaker ", "camera ", "fan ", "light ", "door ", "window ", 
    "floor ", "ceiling "
];